# +----------------------------------------------------+
# <              Permission Configuration              >
# <                                                    >
# <        can be configured using perm command        >
# +----------------------------------------------------+

RoleID:
  RoleName: sample
  Permission: '{-category} {+command}'
